import type { User, Issue, ChecklistTask, Season, ChemicalReading, PoolEquipment, PoolInspection, SeasonalTask } from './types';

export const SEED_USERS: User[] = [
  { id: '10000000-0000-0000-0000-000000000001', name: 'Jordan M.', role: 'doe', initials: 'JM' },
  { id: '10000000-0000-0000-0000-000000000002', name: 'Tom H.', role: 'facilities_manager', initials: 'TH' },
  { id: '10000000-0000-0000-0000-000000000003', name: 'Dana K.', role: 'maintenance_staff', initials: 'DK' },
  { id: '10000000-0000-0000-0000-000000000004', name: 'Mike L.', role: 'maintenance_staff', initials: 'ML' },
];

export const SEED_SEASON: Season = {
  id: '20000000-0000-0000-0000-000000000001',
  name: 'Summer 2025',
  openingDate: '2025-06-23',
  closingDate: '2025-07-18',
  acaInspectionDate: null,
};

// Reference timestamps relative to "today" concept — seeded as fixed ISO strings
const T = {
  now: '2025-06-23T14:00:00.000Z',
  minus1h: '2025-06-23T13:00:00.000Z',
  minus2h: '2025-06-23T12:00:00.000Z',
  minus3h: '2025-06-23T11:00:00.000Z',
  minus4h: '2025-06-23T10:00:00.000Z',
  minus1d: '2025-06-22T14:00:00.000Z',
  minus2d: '2025-06-21T10:00:00.000Z',
  minus3d: '2025-06-20T09:00:00.000Z',
  minus5d: '2025-06-18T08:00:00.000Z',
  minus7d: '2025-06-16T08:00:00.000Z',
  today: '2025-06-23',
  tomorrow: '2025-06-24',
  plus2d: '2025-06-25',
  plus5d: '2025-06-28',
  minus10d: '2025-06-13',
};

export const SEED_ISSUES: Issue[] = [
  {
    id: 'i1',
    title: 'Dock ramp — broken plank, safety hazard',
    description:
      'Third plank from the end is cracked through. Campers using the dock for kayak launch this afternoon. Needs to be roped off or repaired before the 2pm activity block.',
    locations: ['Waterfront'],
    priority: 'urgent',
    status: 'assigned',
    assigneeId: 'u2',
    reportedById: 'u4',
    estimatedCostDisplay: '$380',
    estimatedCostValue: 380,
    actualCost: null,
    photoUrl: null,
    dueDate: T.today,
    isRecurring: false,
    recurringInterval: null,
    createdAt: T.minus2h,
    updatedAt: T.minus1h,
    activityLog: [
      {
        id: 'a1',
        userId: 'u1',
        userName: 'Jordan M.',
        action: 'Assigned to Tom H. for repair',
        timestamp: T.minus1h,
      },
      {
        id: 'a2',
        userId: 'u4',
        userName: 'Mike L.',
        action: 'Issue logged with photo attached',
        timestamp: T.minus2h,
      },
    ],
  },
  {
    id: 'i2',
    title: 'Walk-in refrigerator not holding temperature',
    description:
      'Temp reading 48°F, should be below 40°F. Compressor making intermittent clicking noise. Health code risk — food safety issue. Need emergency HVAC/refrigeration tech.',
    locations: ['Dining Hall'],
    priority: 'urgent',
    status: 'unassigned',
    assigneeId: null,
    reportedById: 'u3',
    estimatedCostDisplay: '$600–1,200',
    estimatedCostValue: 900,
    actualCost: null,
    photoUrl: null,
    dueDate: T.today,
    isRecurring: false,
    recurringInterval: null,
    createdAt: T.minus3h,
    updatedAt: T.minus3h,
    activityLog: [
      {
        id: 'a3',
        userId: 'u3',
        userName: 'Dana K.',
        action: 'Issue logged — refrigerator at 48°F, compressor clicking',
        timestamp: T.minus3h,
      },
    ],
  },
  {
    id: 'i3',
    title: 'Cabin 7 — screen door off hinges',
    description:
      'Screen door in Cabin 7 has come off the bottom hinge. Door is hanging at an angle. Need to re-hang and possibly replace hinge hardware.',
    locations: ['Cabins'],
    priority: 'high',
    status: 'assigned',
    assigneeId: 'u2',
    reportedById: 'u1',
    estimatedCostDisplay: '$45',
    estimatedCostValue: 45,
    actualCost: null,
    photoUrl: null,
    dueDate: T.tomorrow,
    isRecurring: false,
    recurringInterval: null,
    createdAt: T.minus1d,
    updatedAt: T.minus1d,
    activityLog: [
      {
        id: 'a4',
        userId: 'u1',
        userName: 'Jordan M.',
        action: 'Assigned to Tom H.',
        timestamp: T.minus1d,
      },
      {
        id: 'a5',
        userId: 'u1',
        userName: 'Jordan M.',
        action: 'Issue logged',
        timestamp: T.minus1d,
      },
    ],
  },
  {
    id: 'i4',
    title: 'Art barn roof leak above supply storage',
    description:
      'Active drip in the north corner of the Art Barn, directly above the paper and canvas storage. Tarped the supplies temporarily. Need roofer to assess — likely flashing failure.',
    locations: ['Art Barn'],
    priority: 'high',
    status: 'unassigned',
    assigneeId: null,
    reportedById: 'u2',
    estimatedCostDisplay: '$1,200–2,000',
    estimatedCostValue: 1600,
    actualCost: null,
    photoUrl: null,
    dueDate: T.plus2d,
    isRecurring: false,
    recurringInterval: null,
    createdAt: T.minus2d,
    updatedAt: T.minus2d,
    activityLog: [
      {
        id: 'a6',
        userId: 'u2',
        userName: 'Tom H.',
        action: 'Issue logged — vendor TBD, need to source roofer',
        timestamp: T.minus2d,
      },
    ],
  },
  {
    id: 'i5',
    title: 'Pool pump making unusual noise',
    description:
      'Main circulation pump is producing a high-pitched whine during operation. Flow rate appears normal but noise started yesterday. Likely bearing wear — may need pump replacement.',
    locations: ['Aquatics'],
    priority: 'normal',
    status: 'in_progress',
    assigneeId: 'u2',
    reportedById: 'u3',
    estimatedCostDisplay: '$150–250',
    estimatedCostValue: 200,
    actualCost: null,
    photoUrl: null,
    dueDate: T.plus2d,
    isRecurring: false,
    recurringInterval: null,
    createdAt: T.minus1d,
    updatedAt: T.minus4h,
    activityLog: [
      {
        id: 'a7',
        userId: 'u2',
        userName: 'Tom H.',
        action: 'Status changed to In progress — inspecting pump bearings',
        timestamp: T.minus4h,
      },
      {
        id: 'a8',
        userId: 'u3',
        userName: 'Dana K.',
        action: 'Issue logged — pump noise first noticed at 6am',
        timestamp: T.minus1d,
      },
    ],
  },
  {
    id: 'i6',
    title: 'Main lodge — two light fixtures out',
    description:
      'Two overhead fluorescent fixtures in the main lodge common area have failed. Replaced bulbs — no change. Likely ballast issue. Non-urgent but affects evening activities.',
    locations: ['Main Lodge'],
    priority: 'normal',
    status: 'resolved',
    assigneeId: 'u2',
    reportedById: 'u4',
    estimatedCostDisplay: '$30',
    estimatedCostValue: 30,
    actualCost: 28,
    photoUrl: null,
    dueDate: null,
    isRecurring: false,
    recurringInterval: null,
    createdAt: T.minus5d,
    updatedAt: T.minus3d,
    activityLog: [
      {
        id: 'a9',
        userId: 'u2',
        userName: 'Tom H.',
        action: 'Marked resolved — replaced ballasts, $28 actual cost',
        timestamp: T.minus3d,
      },
      {
        id: 'a10',
        userId: 'u2',
        userName: 'Tom H.',
        action: 'Status changed to In progress',
        timestamp: T.minus4h,
      },
      {
        id: 'a11',
        userId: 'u4',
        userName: 'Mike L.',
        action: 'Issue logged',
        timestamp: T.minus5d,
      },
    ],
  },
  {
    id: 'i7',
    title: 'Athletic field irrigation head broken',
    description:
      'One of the pop-up irrigation heads on field 2 is broken — stuck in the up position and spraying sideways. Needs to be replaced before it becomes a trip hazard.',
    locations: ['Athletic Fields'],
    priority: 'normal',
    status: 'unassigned',
    assigneeId: null,
    reportedById: 'u4',
    estimatedCostDisplay: '$120',
    estimatedCostValue: 120,
    actualCost: null,
    photoUrl: null,
    dueDate: T.plus5d,
    isRecurring: false,
    recurringInterval: null,
    createdAt: T.minus2d,
    updatedAt: T.minus2d,
    activityLog: [
      {
        id: 'a12',
        userId: 'u4',
        userName: 'Mike L.',
        action: 'Issue logged',
        timestamp: T.minus2d,
      },
    ],
  },
  {
    id: 'i8',
    title: 'Health center — exam table padding torn',
    description:
      'The vinyl padding on the exam table has a tear approximately 8 inches long on the seat edge. Needs to be replaced before next medical check-in. Infection control concern.',
    locations: ['Health Center'],
    priority: 'high',
    status: 'in_progress',
    assigneeId: 'u3',
    reportedById: 'u3',
    estimatedCostDisplay: '$85',
    estimatedCostValue: 85,
    actualCost: null,
    photoUrl: null,
    dueDate: T.tomorrow,
    isRecurring: false,
    recurringInterval: null,
    createdAt: T.minus3d,
    updatedAt: T.minus1d,
    activityLog: [
      {
        id: 'a13',
        userId: 'u3',
        userName: 'Dana K.',
        action: 'Status changed to In progress — sourcing replacement padding',
        timestamp: T.minus1d,
      },
      {
        id: 'a14',
        userId: 'u3',
        userName: 'Dana K.',
        action: 'Issue logged',
        timestamp: T.minus3d,
      },
    ],
  },
  // Additional resolved issues to bring resolved count up
  {
    id: 'i9',
    title: 'Waterfront dock — loose railing section',
    description: 'South railing section had two loose bolts. Tightened and reinforced.',
    locations: ['Waterfront'],
    priority: 'high',
    status: 'resolved',
    assigneeId: 'u2',
    reportedById: 'u2',
    estimatedCostDisplay: '$0',
    estimatedCostValue: 0,
    actualCost: 0,
    photoUrl: null,
    dueDate: null,
    isRecurring: false,
    recurringInterval: null,
    createdAt: T.minus7d,
    updatedAt: T.minus5d,
    activityLog: [
      {
        id: 'a15',
        userId: 'u2',
        userName: 'Tom H.',
        action: 'Marked resolved — no cost, maintenance only',
        timestamp: T.minus5d,
      },
    ],
  },
  {
    id: 'i10',
    title: 'Dining hall — dishwasher drain clog',
    description: 'Commercial dishwasher draining slowly. Cleared grease buildup from drain line.',
    locations: ['Dining Hall'],
    priority: 'normal',
    status: 'resolved',
    assigneeId: 'u4',
    reportedById: 'u3',
    estimatedCostDisplay: '$50',
    estimatedCostValue: 50,
    actualCost: 45,
    photoUrl: null,
    dueDate: null,
    isRecurring: true,
    recurringInterval: 'monthly',
    createdAt: T.minus10d,
    updatedAt: T.minus7d,
    activityLog: [
      {
        id: 'a16',
        userId: 'u4',
        userName: 'Mike L.',
        action: 'Marked resolved — drain cleared, $45 actual',
        timestamp: T.minus7d,
      },
    ],
  },
];

// ─── Pool seed data ───────────────────────────────────────────────────────────

export const SEED_POOL_READINGS: ChemicalReading[] = [
  { id: 'pr1', freeChlorine: 0.8, ph: 7.4, alkalinity: 88, cyanuricAcid: 38, waterTemp: 74, calciumHardness: null, timeOfDay: '7:30am', loggedById: '10000000-0000-0000-0000-000000000002', loggedByName: 'Tom H.', correctiveAction: null, poolStatus: 'closed_corrective', createdAt: '2025-07-07T07:30:00.000Z' },
  { id: 'pr2', freeChlorine: 1.8, ph: 7.5, alkalinity: 95, cyanuricAcid: 40, waterTemp: 73, calciumHardness: null, timeOfDay: '7:15am', loggedById: '10000000-0000-0000-0000-000000000001', loggedByName: 'Jordan M.', correctiveAction: null, poolStatus: 'open_all_clear', createdAt: '2025-07-06T07:15:00.000Z' },
  { id: 'pr3', freeChlorine: 1.4, ph: 7.6, alkalinity: 94, cyanuricAcid: 40, waterTemp: 76, calciumHardness: null, timeOfDay: '3:00pm', loggedById: '10000000-0000-0000-0000-000000000002', loggedByName: 'Tom H.', correctiveAction: null, poolStatus: 'open_all_clear', createdAt: '2025-07-06T15:00:00.000Z' },
  { id: 'pr4', freeChlorine: 2.1, ph: 7.4, alkalinity: 98, cyanuricAcid: 39, waterTemp: 72, calciumHardness: null, timeOfDay: '7:20am', loggedById: '10000000-0000-0000-0000-000000000001', loggedByName: 'Jordan M.', correctiveAction: null, poolStatus: 'open_all_clear', createdAt: '2025-07-05T07:20:00.000Z' },
  { id: 'pr5', freeChlorine: 2.4, ph: 7.9, alkalinity: 100, cyanuricAcid: 42, waterTemp: 75, calciumHardness: null, timeOfDay: '7:10am', loggedById: '10000000-0000-0000-0000-000000000002', loggedByName: 'Tom H.', correctiveAction: null, poolStatus: 'open_all_clear', createdAt: '2025-07-04T07:10:00.000Z' },
  { id: 'pr6', freeChlorine: 1.9, ph: 7.5, alkalinity: 102, cyanuricAcid: 41, waterTemp: 73, calciumHardness: null, timeOfDay: '7:30am', loggedById: '10000000-0000-0000-0000-000000000001', loggedByName: 'Jordan M.', correctiveAction: null, poolStatus: 'open_all_clear', createdAt: '2025-07-03T07:30:00.000Z' },
  { id: 'pr7', freeChlorine: 2.2, ph: 7.3, alkalinity: 105, cyanuricAcid: 38, waterTemp: 71, calciumHardness: null, timeOfDay: '7:00am', loggedById: '10000000-0000-0000-0000-000000000002', loggedByName: 'Tom H.', correctiveAction: null, poolStatus: 'open_all_clear', createdAt: '2025-07-02T07:00:00.000Z' },
];

export const SEED_POOL_EQUIPMENT: PoolEquipment[] = [
  { id: 'pe1', name: 'Main circulation pump', type: 'pump', status: 'warn', statusDetail: 'Unusual noise', lastServiced: '2025-05-15', nextServiceDue: '2025-07-10', vendor: 'AquaPro Services', specs: '1.5 HP', createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-06T00:00:00.000Z' },
  { id: 'pe2', name: 'Sand filter system', type: 'filter', status: 'ok', statusDetail: 'Normal', lastServiced: '2025-07-03', nextServiceDue: '2025-07-10', vendor: 'AquaPro Services', specs: '48" tank', createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-03T00:00:00.000Z' },
  { id: 'pe3', name: 'Pool heater', type: 'heater', status: 'warn', statusDetail: 'Operational', lastServiced: '2025-01-10', nextServiceDue: '2025-07-21', vendor: 'AquaPro Services', specs: '400k BTU', createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-01-10T00:00:00.000Z' },
  { id: 'pe4', name: 'Automatic chlorinator', type: 'chlorinator', status: 'ok', statusDetail: 'Low — refill soon', lastServiced: '2025-07-01', nextServiceDue: null, vendor: null, specs: null, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-01T00:00:00.000Z' },
  { id: 'pe5', name: 'Safety & rescue equipment', type: 'safety', status: 'ok', statusDetail: 'All present', lastServiced: '2025-06-21', nextServiceDue: null, vendor: null, specs: null, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-21T00:00:00.000Z' },
];

export const SEED_POOL_INSPECTIONS: PoolInspection[] = [
  { id: 'pi1', name: 'Health dept. water quality inspection', frequency: 'Every 30 days', authority: 'County Health Department', standard: 'State law required', status: 'overdue', lastCompleted: '2025-06-04', nextDue: '2025-07-04', history: ['Jun 4', 'May 5', 'Apr 7'], createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-07T00:00:00.000Z' },
  { id: 'pi2', name: 'ACA waterfront safety inspection', frequency: 'Weekly during session', authority: 'Internal', standard: 'ACA Standard WS-4', status: 'due', lastCompleted: '2025-07-02', nextDue: '2025-07-09', history: ['Jul 2', 'Jun 25', 'Jun 18', 'Jun 11'], createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-02T00:00:00.000Z' },
  { id: 'pi3', name: 'Pool equipment monthly service check', frequency: 'Monthly', authority: 'AquaPro Services', standard: null, status: 'due', lastCompleted: '2025-06-15', nextDue: '2025-07-15', history: ['Jun 15', 'May 15', 'Apr 15'], createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-15T00:00:00.000Z' },
  { id: 'pi4', name: 'Lifeguard certification verification', frequency: 'Before each session', authority: 'ACA & Red Cross', standard: null, status: 'ok', lastCompleted: '2025-06-21', nextDue: '2025-08-31', history: ['Alex R.', 'Sam K.', 'Dana L.', 'Chris M.'], createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-21T00:00:00.000Z' },
  { id: 'pi5', name: 'Pre-season pool opening inspection', frequency: 'Annual', authority: 'Jordan M. + AquaPro', standard: null, status: 'ok', lastCompleted: '2025-06-18', nextDue: '2026-05-01', history: ['Structural', 'Equipment', 'Safety gear', 'Water quality'], createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-18T00:00:00.000Z' },
];

export const SEED_POOL_SEASONAL_TASKS: SeasonalTask[] = [
  // Opening (8 tasks, all complete)
  { id: 'st1', title: 'Remove pool cover and inspect for winter damage', detail: null, phase: 'opening', isComplete: true, completedBy: 'Tom H.', completedDate: '2025-06-01', assignees: ['Tom H.'], sortOrder: 1, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-01T00:00:00.000Z' },
  { id: 'st2', title: 'Inspect pool shell, coping, and tile for cracks or damage', detail: null, phase: 'opening', isComplete: true, completedBy: 'Tom H.', completedDate: '2025-06-03', assignees: ['Tom H.', 'Vendor'], sortOrder: 2, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-03T00:00:00.000Z' },
  { id: 'st3', title: 'Reconnect and prime all equipment — pump, filter, heater', detail: null, phase: 'opening', isComplete: true, completedBy: 'AquaPro Services', completedDate: '2025-06-05', assignees: ['AquaPro Services'], sortOrder: 3, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-05T00:00:00.000Z' },
  { id: 'st4', title: 'Shock pool and balance all chemical levels', detail: null, phase: 'opening', isComplete: true, completedBy: 'Jordan M.', completedDate: '2025-06-10', assignees: ['Jordan M.'], sortOrder: 4, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-10T00:00:00.000Z' },
  { id: 'st5', title: 'Verify all safety equipment present and in good condition', detail: null, phase: 'opening', isComplete: true, completedBy: 'Jordan M.', completedDate: '2025-06-12', assignees: ['Jordan M.'], sortOrder: 5, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-12T00:00:00.000Z' },
  { id: 'st6', title: 'Verify all lifeguard certifications current', detail: null, phase: 'opening', isComplete: true, completedBy: 'Jordan M.', completedDate: '2025-06-14', assignees: ['Jordan M.'], sortOrder: 6, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-14T00:00:00.000Z' },
  { id: 'st7', title: 'Pass health department pre-season inspection', detail: null, phase: 'opening', isComplete: true, completedBy: 'Jordan M.', completedDate: '2025-06-18', assignees: ['Jordan M.'], sortOrder: 7, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-18T00:00:00.000Z' },
  { id: 'st8', title: 'Post all required signage — depth markers, rules, emergency contacts', detail: null, phase: 'opening', isComplete: true, completedBy: 'Tom H.', completedDate: '2025-06-20', assignees: ['Tom H.'], sortOrder: 8, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-20T00:00:00.000Z' },
  // In-season (13 tasks, 9 done, 4 open)
  { id: 'st9',  title: 'Daily chemical readings — AM and PM', detail: '2x daily during session · automated reminder at 7am and 2pm', phase: 'in_season', isComplete: true, completedBy: null, completedDate: null, assignees: [], sortOrder: 1, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-07T00:00:00.000Z' },
  { id: 'st10', title: 'Weekly ACA waterfront inspection', detail: null, phase: 'in_season', isComplete: true, completedBy: 'Jordan M.', completedDate: '2025-07-02', assignees: ['Jordan M.'], sortOrder: 2, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-02T00:00:00.000Z' },
  { id: 'st11', title: 'Backwash sand filter', detail: null, phase: 'in_season', isComplete: true, completedBy: 'Tom H.', completedDate: '2025-07-03', assignees: ['Tom H.'], sortOrder: 3, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-03T00:00:00.000Z' },
  { id: 'st12', title: 'Weekly equipment visual inspection', detail: null, phase: 'in_season', isComplete: true, completedBy: 'Tom H.', completedDate: '2025-07-04', assignees: ['Tom H.'], sortOrder: 4, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-04T00:00:00.000Z' },
  { id: 'st13', title: 'Verify lifeguard daily sign-in complete', detail: null, phase: 'in_season', isComplete: true, completedBy: 'Jordan M.', completedDate: '2025-07-05', assignees: ['Jordan M.'], sortOrder: 5, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-05T00:00:00.000Z' },
  { id: 'st14', title: 'Check pool deck surface for hazards', detail: null, phase: 'in_season', isComplete: true, completedBy: 'Tom H.', completedDate: '2025-07-05', assignees: ['Tom H.'], sortOrder: 6, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-07-05T00:00:00.000Z' },
  { id: 'st15', title: 'Test emergency phone and communication system', detail: null, phase: 'in_season', isComplete: true, completedBy: 'Jordan M.', completedDate: '2025-06-30', assignees: ['Jordan M.'], sortOrder: 7, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-30T00:00:00.000Z' },
  { id: 'st16', title: 'Inspect and lubricate gate and fence hardware', detail: null, phase: 'in_season', isComplete: true, completedBy: 'Tom H.', completedDate: '2025-06-28', assignees: ['Tom H.'], sortOrder: 8, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-28T00:00:00.000Z' },
  { id: 'st17', title: 'Clean and inspect pool deck furniture', detail: null, phase: 'in_season', isComplete: true, completedBy: 'Tom H.', completedDate: '2025-06-27', assignees: ['Tom H.'], sortOrder: 9, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-06-27T00:00:00.000Z' },
  { id: 'st18', title: 'Monthly health department water quality inspection', detail: 'County required · Currently overdue — contact county health office', phase: 'in_season', isComplete: false, completedBy: null, completedDate: null, assignees: ['Jordan M.'], sortOrder: 10, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  { id: 'st19', title: 'Monthly equipment service — AquaPro', detail: null, phase: 'in_season', isComplete: false, completedBy: null, completedDate: null, assignees: ['AquaPro Services'], sortOrder: 11, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  { id: 'st20', title: 'Refill chlorine tablet feeder', detail: 'Tablet level currently low', phase: 'in_season', isComplete: false, completedBy: null, completedDate: null, assignees: ['Tom H.'], sortOrder: 12, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  { id: 'st21', title: 'Pump motor service — unusual noise investigation', detail: null, phase: 'in_season', isComplete: false, completedBy: null, completedDate: null, assignees: ['AquaPro Services'], sortOrder: 13, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  // Closing (8 tasks, 0 done)
  { id: 'st22', title: 'Superchlorinate pool before closing', detail: 'Scheduled for Aug 10 after last swim period', phase: 'closing', isComplete: false, completedBy: null, completedDate: null, assignees: [], sortOrder: 1, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  { id: 'st23', title: 'Drain pool to winter level and plug returns', detail: null, phase: 'closing', isComplete: false, completedBy: null, completedDate: null, assignees: [], sortOrder: 2, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  { id: 'st24', title: 'Blow out all plumbing lines — winterize', detail: null, phase: 'closing', isComplete: false, completedBy: null, completedDate: null, assignees: ['AquaPro Services'], sortOrder: 3, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  { id: 'st25', title: 'Remove, clean, and store all safety equipment', detail: null, phase: 'closing', isComplete: false, completedBy: null, completedDate: null, assignees: [], sortOrder: 4, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  { id: 'st26', title: 'End-of-season equipment inspection and service report', detail: null, phase: 'closing', isComplete: false, completedBy: null, completedDate: null, assignees: ['AquaPro Services'], sortOrder: 5, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  { id: 'st27', title: 'Install winter safety cover', detail: null, phase: 'closing', isComplete: false, completedBy: null, completedDate: null, assignees: [], sortOrder: 6, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  { id: 'st28', title: 'Document end-of-season condition report with photos', detail: null, phase: 'closing', isComplete: false, completedBy: null, completedDate: null, assignees: [], sortOrder: 7, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
  { id: 'st29', title: 'Final health department close-out inspection', detail: null, phase: 'closing', isComplete: false, completedBy: null, completedDate: null, assignees: ['Jordan M.'], sortOrder: 8, createdAt: '2025-04-01T00:00:00.000Z', updatedAt: '2025-04-01T00:00:00.000Z' },
];

export const SEED_TASKS: ChecklistTask[] = [
  // Pre-camp tasks
  {
    id: 't1',
    title: 'Inspect all cabin beds and mattresses',
    description:
      'Check all bunk frames for structural integrity, inspect mattresses for damage or mold. Replace any mattresses that fail inspection.',
    locations: ['Cabins'],
    priority: 'high',
    status: 'complete',
    assigneeId: 'u2',
    phase: 'pre',
    daysRelativeToOpening: -21,
    dueDate: '2025-06-02',
    isRecurring: true,
    createdAt: T.minus7d,
    updatedAt: T.minus7d,
    activityLog: [
      {
        id: 'ta1',
        userId: 'u2',
        userName: 'Tom H.',
        action: 'Marked complete — all 48 bunks inspected, 3 mattresses replaced',
        timestamp: T.minus7d,
      },
    ],
  },
  {
    id: 't2',
    title: 'Waterfront dock safety inspection',
    description:
      'Full structural inspection of main dock, kayak launch, and swim area roping. Check all hardware, flotation, and safety equipment.',
    locations: ['Waterfront'],
    priority: 'urgent',
    status: 'complete',
    assigneeId: 'u2',
    phase: 'pre',
    daysRelativeToOpening: -14,
    dueDate: '2025-06-09',
    isRecurring: true,
    createdAt: T.minus5d,
    updatedAt: T.minus5d,
    activityLog: [
      {
        id: 'ta2',
        userId: 'u2',
        userName: 'Tom H.',
        action: 'Marked complete — dock passed inspection, one plank flagged for monitoring',
        timestamp: T.minus5d,
      },
    ],
  },
  {
    id: 't3',
    title: 'Test all smoke and CO detectors',
    description:
      'Test every smoke detector and carbon monoxide detector in all buildings. Replace batteries in all units regardless of current charge. Log results.',
    locations: ['Main Lodge'],
    priority: 'urgent',
    status: 'complete',
    assigneeId: 'u4',
    phase: 'pre',
    daysRelativeToOpening: -7,
    dueDate: '2025-06-16',
    isRecurring: true,
    createdAt: T.minus3d,
    updatedAt: T.minus3d,
    activityLog: [
      {
        id: 'ta3',
        userId: 'u4',
        userName: 'Mike L.',
        action: 'Marked complete — 34 units tested, all pass, batteries replaced',
        timestamp: T.minus3d,
      },
    ],
  },
  {
    id: 't4',
    title: 'Deep clean dining hall kitchen equipment',
    description:
      'Commercial deep clean of all cooking equipment, hoods, filters, walk-in cooler/freezer, and dishwashing station. Must pass health inspection standard.',
    locations: ['Dining Hall'],
    priority: 'high',
    status: 'complete',
    assigneeId: 'u3',
    phase: 'pre',
    daysRelativeToOpening: -10,
    dueDate: '2025-06-13',
    isRecurring: true,
    createdAt: T.minus5d,
    updatedAt: T.minus5d,
    activityLog: [
      {
        id: 'ta4',
        userId: 'u3',
        userName: 'Dana K.',
        action: 'Marked complete — full kitchen deep clean done, health-inspection ready',
        timestamp: T.minus5d,
      },
    ],
  },
  {
    id: 't5',
    title: 'Pool chemistry baseline and shock treatment',
    description:
      'Test all pool water parameters (pH, chlorine, alkalinity, cyanuric acid). Perform opening shock treatment. Verify all safety equipment in place.',
    locations: ['Aquatics'],
    priority: 'urgent',
    status: 'in_progress',
    assigneeId: 'u2',
    phase: 'pre',
    daysRelativeToOpening: -5,
    dueDate: '2025-06-18',
    isRecurring: true,
    createdAt: T.minus2d,
    updatedAt: T.minus1d,
    activityLog: [
      {
        id: 'ta5',
        userId: 'u2',
        userName: 'Tom H.',
        action: 'Status changed to In progress — initial chemistry test done, shock treatment scheduled',
        timestamp: T.minus1d,
      },
    ],
  },
  {
    id: 't6',
    title: 'Restock health center supplies',
    description:
      'Inventory all first aid supplies, medications (where permitted), and medical equipment. Restock to opening-day par levels. Check all expiration dates.',
    locations: ['Health Center'],
    priority: 'normal',
    status: 'pending',
    assigneeId: 'u3',
    phase: 'pre',
    daysRelativeToOpening: -3,
    dueDate: '2025-06-20',
    isRecurring: true,
    createdAt: T.minus1d,
    updatedAt: T.minus1d,
    activityLog: [],
  },
  {
    id: 't7',
    title: 'Paint touch-up on cabin exteriors',
    description:
      'Touch up peeling or damaged exterior paint on all cabin buildings. Focus on trim, door frames, and shutters. Use color-matched paint from maintenance storage.',
    locations: ['Cabins'],
    priority: 'normal',
    status: 'pending',
    assigneeId: null,
    phase: 'pre',
    daysRelativeToOpening: -14,
    dueDate: '2025-06-09',
    isRecurring: true,
    createdAt: T.minus7d,
    updatedAt: T.minus7d,
    activityLog: [],
  },
  {
    id: 't8',
    title: 'Athletic field line marking',
    description:
      'Re-stripe all athletic field boundary lines, penalty areas, and center markings. Use field-safe chalk or paint. Include basketball court and volleyball court.',
    locations: ['Athletic Fields'],
    priority: 'normal',
    status: 'pending',
    assigneeId: null,
    phase: 'pre',
    daysRelativeToOpening: -2,
    dueDate: '2025-06-21',
    isRecurring: true,
    createdAt: T.minus1d,
    updatedAt: T.minus1d,
    activityLog: [],
  },
  // Post-camp tasks
  {
    id: 't9',
    title: 'Drain and winterize pool',
    description:
      'Lower pool water level, add winterizing chemicals, blow out all lines, install winter cover. Drain all pumps and filters. Document closing chemistry readings.',
    locations: ['Aquatics'],
    priority: 'high',
    status: 'pending',
    assigneeId: 'u2',
    phase: 'post',
    daysRelativeToOpening: 3,
    dueDate: '2025-07-21',
    isRecurring: true,
    createdAt: T.minus7d,
    updatedAt: T.minus7d,
    activityLog: [],
  },
  {
    id: 't10',
    title: 'Deep clean all cabins',
    description:
      'Full deep clean of all cabin interiors: sweep, mop, wipe down all surfaces, clean windows, launder linens. Remove all personal items left by campers.',
    locations: ['Cabins'],
    priority: 'high',
    status: 'pending',
    assigneeId: null,
    phase: 'post',
    daysRelativeToOpening: 2,
    dueDate: '2025-07-20',
    isRecurring: true,
    createdAt: T.minus7d,
    updatedAt: T.minus7d,
    activityLog: [],
  },
  {
    id: 't11',
    title: 'Inventory and store athletic equipment',
    description:
      'Count and condition-check all athletic equipment. Clean and store in proper storage areas. Flag any items needing replacement before next season.',
    locations: ['Athletic Fields'],
    priority: 'normal',
    status: 'pending',
    assigneeId: 'u4',
    phase: 'post',
    daysRelativeToOpening: 5,
    dueDate: '2025-07-23',
    isRecurring: true,
    createdAt: T.minus7d,
    updatedAt: T.minus7d,
    activityLog: [],
  },
  {
    id: 't12',
    title: 'Roof and gutter inspection before winter',
    description:
      'Inspect all building roofs for damage, missing shingles, or flashing issues. Clean all gutters and downspouts. Seal any gaps before winter weather.',
    locations: ['Main Lodge'],
    priority: 'high',
    status: 'pending',
    assigneeId: null,
    phase: 'post',
    daysRelativeToOpening: 7,
    dueDate: '2025-07-25',
    isRecurring: true,
    createdAt: T.minus7d,
    updatedAt: T.minus7d,
    activityLog: [],
  },
];
