-- Enable realtime for all tables that have subscription handlers in the web app
ALTER PUBLICATION supabase_realtime ADD TABLE
  checklist_tasks,
  checklist_activity,
  issues,
  issue_activity,
  pools,
  pool_chemical_readings,
  pool_equipment,
  pool_service_log,
  pool_seasonal_tasks,
  pool_inspections,
  pool_inspection_log,
  camp_assets,
  asset_checkouts,
  asset_service_records,
  asset_maintenance_tasks,
  safety_items,
  safety_inspection_log,
  safety_drills,
  safety_staff,
  staff_certifications,
  safety_temp_logs,
  safety_licenses;
