-- Fourteen Westchester obligations that were not in the module.
--
-- Chapter 873 Article XVIII is the county's own camp article and it goes past the state code in
-- several places a camp gets caught on: the annual workshop is a permit gate with a penalty
-- attached, two non-relative written references are required per employee before their first day,
-- and nonswimmers have to be visually distinguishable. None of these print on a form, which is
-- exactly why they were missing -- the module only knew about obligations that appeared on a
-- document we render.
--
-- Article XII (pools and beaches) was rewritten in the 5 August 2025 approval, and the AED
-- collaborative agreement in §873.1204 is the sharpest new duty in it.
--
-- WC-30 lands as `needs_verification` on purpose. The animal facility article plainly reaches a
-- stable, but whether the county issues a separate permit for a camp's own barn is a question for
-- the county, and the module says so rather than inventing an answer.

begin;

with p as (select id from compliance_profiles where code = 'NY-WESTCHESTER'),
     a as (select id from compliance_authorities where code = 'WESTCHESTER-DOH'),
     s873 as (select id from compliance_sources where source_key = 'ch873'),
     samu as (select id from compliance_sources where source_key = 'amuse_factsheet'),
     ssor as (select id from compliance_sources where source_key = 'sor_factsheet')
insert into compliance_requirements
 (profile_id, authority_id, req_code, label, summary, category, evidence_type, evidence_rule,
  evidence_hint, frequency, applies_when, citation, citation_url, verify_status, sort_order,
  source_id, source_checked_on, form_codes, holds_personal_records)
values
 ((select id from p),(select id from a),'WC-20','Attend the annual county children''s camp workshop',
  'The camp director, assistant director or operator must attend. Failure is a code violation, carries a penalty, and requires attending a video presentation of the workshop. A permit will be denied until both are done.',
  'permit','training','{"kind":"county_workshop"}'::jsonb,
  'Record who attended and when.','annual','{}'::jsonb,
  'Westchester County Sanitary Code §873.1801',
  'https://health.westchestercountyny.gov/forms-and-permits/camp-operator','verified',200,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-21','Two written references for every prospective employee',
  'Obtained, reviewed and evaluated before employment begins. Neither reference may be a relative. The written record of satisfactory completion is kept on file for the department.',
  'personnel','screening','{"kind":"reference_check"}'::jsonb,
  'Two non-relative references per person, before their first day.','per_session','{}'::jsonb,
  'Westchester County Sanitary Code §873.1804',
  'https://health.westchestercountyny.gov/forms-and-permits/camp-operator','verified',210,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-22','Make nonswimmers readily distinguishable',
  'A camper assessed as a nonswimmer must be distinguishable from an intermediate or swimmer by a conspicuously coloured bathing cap, headband, wrist tag or another method the county accepts.',
  'supervision','plan_section','{"section_codes":["ACT-07"]}'::jsonb,
  'Describe the method in the swimming section of your plan.','annual',
  '{"any_of":{"has_pool":"true","has_waterfront":"true"}}'::jsonb,
  'Westchester County Sanitary Code §873.1800',
  'https://health.westchestercountyny.gov/forms-and-permits/camp-operator','verified',220,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-23','Off-site swimming: lifeguard ratio, identification and counselors in the water',
  'One qualified lifeguard per 25 bathers. Lifeguards in garments identified with the camp name. Counselors in the water directly supervising nonswimmers at 1:10 over age 8, 1:8 under 8 and 1:6 under 6.',
  'supervision','plan_section','{"section_codes":["ACT-09"]}'::jsonb,
  'Covered by the off-site swimming section of your plan.','annual',
  '{"offers_offsite_swim":"true"}'::jsonb,
  'Westchester County Sanitary Code §873.1802',
  'https://health.westchestercountyny.gov/forms-and-permits/camp-operator','verified',230,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-24','Hold an AED under a written collaborative agreement',
  'Every pool and beach operator must acquire and operate an AED under a written agreement with an emergency health care provider, file a copy with NYSDOH, notify the regional council before operating it, post signage at the main entrance, and keep one person on site trained within the preceding 24 months.',
  'facility','document','{}'::jsonb,
  'The collaborative agreement, and your trained person''s certificate.','annual',
  '{"any_of":{"has_pool":"true","has_waterfront":"true"}}'::jsonb,
  'Westchester County Sanitary Code §873.1204',
  'https://health.westchestercountyny.gov/forms-and-permits/camp-operator','verified',240,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-25','Name a qualified swimming pool treatment operator',
  'A pool larger than 1,000 square feet, or one disinfected with gas chlorine, must be maintained by an operator holding a NYSDOH Water Treatment Plant Operator Certification Type A or B, or an adequate equivalent course.',
  'personnel','document','{}'::jsonb,
  'The operator''s certificate.','annual','{"has_pool":"true"}'::jsonb,
  'Westchester County Sanitary Code §873.1202',
  'https://health.westchestercountyny.gov/forms-and-permits/camp-operator','verified',250,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-26','Post the pool safety signage and provide a free 911 telephone',
  'A separate sign at all entrances and within the pool area, red letters at least 4 inches high and 1.5 inches wide. Children under 14 accompanied by an adult. A free, readily accessible telephone in the pool area with posted instructions in characters at least 3 inches.',
  'facility','inspection','{"categories":["water"]}'::jsonb,
  'Checked on site by the county.','ongoing','{"has_pool":"true"}'::jsonb,
  'Westchester County Sanitary Code §873.1203',
  'https://health.westchestercountyny.gov/forms-and-permits/camp-operator','verified',260,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-27','Hold a county food service permit for the camp kitchen',
  'No food service establishment may operate without a county permit. Apply at least 21 days before starting operation. The permit is displayed where the consumer can see it. A camp kitchen is not in the exemption list.',
  'food','permit','{"license_type":"food_service"}'::jsonb,
  'The permit, and where it is displayed.','annual','{"has_kitchen":"true"}'::jsonb,
  'Westchester County Sanitary Code §873.441; 10 NYCRR 14-1.190',
  'https://regs.health.ny.gov/content/subpart-14-1-food-service-establishments','verified',270,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-28','Hold a county permit for your water supply system',
  'A camp running its own water system needs a permit, an operator meeting department qualifications, complete daily records of treatment and disinfection on department forms, and a copy forwarded to the department within ten days of each month''s end.',
  'water','permit','{"license_type":"water_system"}'::jsonb,
  'The permit, and the monthly filing.','annual','{"water_source":"well"}'::jsonb,
  'Westchester County Sanitary Code §873.710',
  'https://health.westchestercountyny.gov/forms-and-permits/camp-operator','verified',280,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-29','Complete the seasonal water supply start-up procedure',
  'For each operational period, before serving water to the public, a seasonal system must demonstrate completion of a state approved start-up procedure.',
  'water','document','{}'::jsonb,
  'The completed start-up procedure.','annual','{"water_source":"well"}'::jsonb,
  '10 NYCRR 5-1.25(b)',
  'https://regs.health.ny.gov/content/subpart-5-1-public-water-supplies','verified',290,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-30','Confirm whether a stable or petting zoo needs an animal facility permit',
  'The county animal facility article reaches a place of public exhibition of live animals and a stable. The annual fee is $120 for a stable. Whether the county permits camp stables separately in practice is a question for them.',
  'facility','attestation','{}'::jsonb,
  'Confirm with the county, then record the answer.','annual',
  '{"has_equestrian":"true"}'::jsonb,
  'Westchester County Sanitary Code §873.1903, §873.2108',
  'https://health.westchestercountyny.gov/forms-and-permits/camp-operator','needs_verification',300,
  (select id from s873),'2026-08-31','{}',false),
 ((select id from p),(select id from a),'WC-31','Inspect every covered amusement device before use each year',
  'Zip lines, high rope courses, climbing walls with mechanical belays, canopy tours, water slides 20 feet or taller and giant swings must be inspected before use each year by an ACCT accredited professional vendor member, a NAARSO certified person, a professional engineer or another qualified third party. Every deficiency is corrected before use.',
  'recreation','document','{}'::jsonb,
  'The inspection report, dated before first use.','annual',
  '{"has_challenge_course":"true"}'::jsonb,
  'NYSDOH/NYSDOL memorandum of understanding; 12 NYCRR Part 45',
  'https://www.health.ny.gov/environmental/outdoors/camps/docs/amuse.pdf','verified',310,
  (select id from samu),'2026-08-31','{"HD-91"}',false),
 ((select id from p),(select id from a),'WC-32','Prove $1,000,000 amusement device liability cover to the county',
  'Annually before use, provide the local health department with proof of insurance of not less than $1,000,000 per occurrence, or a bond of not less than $2,500,000 in the aggregate.',
  'recreation','insurance',
  '{"kind":"amusement_device_liability","min_per_occurrence_cents":100000000,"must_file":"true"}'::jsonb,
  'The certificate, filed with the county.','annual',
  '{"has_challenge_course":"true"}'::jsonb,
  'NYSDOH/NYSDOL memorandum of understanding',
  'https://www.health.ny.gov/environmental/outdoors/camps/docs/amuse.pdf','verified',320,
  (select id from samu),'2026-08-31','{"HD-91"}',false),
 ((select id from p),(select id from a),'WC-33','Search the federal registry, and cover anyone who frequents the camp',
  'Westchester requires all camp staff, volunteers and persons who frequent the camp to be run through the NYS Sex Offender Registry and the Dru Sjodin National Sex Offender Public Website advanced search, with evidence of the search maintained on site.',
  'personnel','screening','{"kind":"nsopw"}'::jsonb,
  'The date each search was run. Never the result.','annual','{}'::jsonb,
  'Westchester County DOH camp operator page',
  'https://health.westchestercountyny.gov/forms-and-permits/camp-operator','verified',330,
  (select id from ssor),'2026-08-31','{}',true)
on conflict (profile_id, req_code) do nothing;

commit;
